### PR TITLE
Texturing for main components

### PR DESCRIPTION
**Pull request by ylt1215**

### CODE REVIEW

**Comment by ch904** [comment]
lgtm

**Comment by cyh0530-1** [comment]
Do you plan to add texture for the computer lab behind the interview rooms on this PR?

**Comment by ylt1215** [comment]
> Do you plan to add texture for the computer lab behind the interview rooms on this PR?

Maybe not at this point, since our implementations for MVP don't include lab rooms.

**Comment by cyh0530-1** [comment]
ok

**Pull request merged**
